### ISSUE TITLE
Paper Summarization

### ISSUE THREAD

**Issue by chuiyunjun** [chuiyunjun/aps490#3]
Research after topic is determined. Everyone could share findings and summarize papers everyone read (including Prof. Lee recommended)

**Comment by grasscutterswife** [comment]
[LitReview-A review of data mining technologies in building energy systems-Anoja.docx](https://github.com/chuiyunjun/aps490/files/7255029/LitReview-A.review.of.data.mining.technologies.in.building.energy.systems-Anoja.docx)

**Comment by chuiyunjun** [comment]
> [LitReview-A review of data mining technologies in building energy systems-Anoja.docx](https://github.com/chuiyunjun/aps490/files/7255029/LitReview-A.review.of.data.mining.technologies.in.building.energy.systems-Anoja.docx)

**Comment by chuiyunjun** [comment]
Added your summary to our wiki page. Thank you @grasscutterswife !! . 
https://github.com/chuiyunjun/aps490/wiki/A-review-of-data-mining-technologies-in-building-energy-systems:-Load-prediction,-pattern-identification,-fault-detection-and-diagnosis
